canal_tp_media_manager_add_media:
    pattern:  /MediaManager/add
    defaults: { _controller: CanalTPMediaManagerBundle:Media:add }
canal_tp_media_manager_delete_media:
    pattern:  /MediaManager/{type}/{basename}/delete
    defaults: { _controller: CanalTPMediaManagerBundle:Media:delete }
canal_tp_media_manager_all_media:
    pattern:  /MediaManager/list
    defaults: { _controller: CanalTPMediaManagerBundle:Media:list }
