parameters:
#    canal_tp_media_manager.example.class: CanalTP\MediaManagerBundle\Example

services:
#    canal_tp_media_manager.example:
#        class: %canal_tp_media_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

